# Generated by Django 2.2.24 on 2022-03-04 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Company Name', max_length=200, verbose_name='Company Name')),
                ('phone_num', models.CharField(default='000-000-000', max_length=12, verbose_name='Phone Number')),
                ('ceo_name', models.CharField(max_length=50, verbose_name='CEO')),
                ('num_employees', models.IntegerField(default=0, verbose_name='Number of Employees')),
                ('maintenance_schedule', models.CharField(max_length=100, verbose_name='maintenance schedule')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Soft_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Soft_Service', max_length=250, verbose_name='Soft_Service')),
                ('security_crew_title', models.CharField(max_length=200)),
                ('cleaning_crew_title', models.CharField(max_length=200)),
                ('landscaping_crew_title', models.CharField(max_length=200)),
                ('caterer', models.CharField(max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Safety_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Safety_Service', max_length=250, verbose_name='Safety_Service')),
                ('training_schedule', models.DurationField(verbose_name='training schedule')),
                ('audit_schedule', models.DurationField(verbose_name='audit schedule')),
                ('saftety_meetings', models.DateTimeField(verbose_name='meeting schedule')),
                ('safety_coordinator', models.CharField(max_length=150)),
                ('job_safety_analysis', models.CharField(max_length=500)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Address', max_length=250, verbose_name='Address')),
                ('address2', models.CharField(max_length=250, verbose_name='Address 2')),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('zipcode', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Leasee', max_length=150, verbose_name='Leasee')),
                ('rate', models.FloatField(default=0.0)),
                ('date', models.DateField(verbose_name='Start Date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Location')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Hard_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Hard_Service', max_length=250, verbose_name='Hard_Service')),
                ('electric_provider', models.CharField(max_length=200)),
                ('plumbing_provider', models.CharField(max_length=200)),
                ('hvac_provider', models.CharField(max_length=200)),
                ('mechanical_provider', models.CharField(max_length=200)),
                ('fire_safety_provider', models.CharField(max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
    ]
