# Generated by Django 2.2.24 on 2022-03-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='owner',
        ),
    ]
