# Generated by Django 2.2.24 on 2022-08-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20220816_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safety_service',
            old_name='saftety_meetings',
            new_name='safety_meetings',
        ),
    ]
